mailboxes: Better locking code
This uses actual real locks that will be auto-unlocked when the process
exits, or the machine reboots. So even on a script crash or a power
failure, there should be no lock file present that blocks all syncs
forever.

diff --git a/bin/mailboxes b/bin/mailboxes
--- a/bin/mailboxes
+++ b/bin/mailboxes
@@ -86,40 +86,41 @@ perform_box_sync() {
   local box="$1"
   local lockfile="${mail_dir}/${box}/.mailboxes-lock"
   local name
+  local lock_fd
   name="$(get_box_name "$box")"
 
   echo "= ${name} ="
 
-  if aquire_lock "$lockfile"; then
-    unread_before="$(write_status "$box" "痢")"
+  exec {lock_fd}>"$lockfile"
+  flock -n "$lock_fd" || { echo "Lock present. Aborting." >&2; return 0; }
+  unread_before="$(write_status "$box" "痢")"
 
-    # Initial index makes sure that changes made locally will be applied to the
-    # server when it is finally synced.
-    echo "Indexing local messages"
-    index_and_tag_emails "$box"
+  # Initial index makes sure that changes made locally will be applied to the
+  # server when it is finally synced.
+  echo "Indexing local messages"
+  index_and_tag_emails "$box"
 
-    echo "Syncing with remote"
-    verbose mbsync --config "$mbsync_config" "$box"
+  echo "Syncing with remote"
+  verbose mbsync --config "$mbsync_config" "$box"
 
-    # Then index again in case any new messages were downloaded from the
-    # server, or emails were moved server-side before the sync started.
-    echo "Indexing messages again"
-    index_and_tag_emails "$box"
+  # Then index again in case any new messages were downloaded from the
+  # server, or emails were moved server-side before the sync started.
+  echo "Indexing messages again"
+  index_and_tag_emails "$box"
 
-    unread_after="$(write_status "$box")"
-    new_email=$((unread_after - unread_before))
-    if [[ $new_email -gt 0 ]]; then
-      notify-send \
-        --icon /usr/share/icons/oxygen/base/32x32/actions/mail-message-new.png \
-        --urgency low \
-        --category email.arrived \
-        --app-name "mailboxes" \
-        "New email in ${name}" \
-        "You have ${new_email} new email(s) in ${name}. Total unread is ${unread_after}."
-    fi
-
-    unlock "$lockfile"
+  unread_after="$(write_status "$box")"
+  new_email=$((unread_after - unread_before))
+  if [[ $new_email -gt 0 ]]; then
+    notify-send \
+      --icon /usr/share/icons/oxygen/base/32x32/actions/mail-message-new.png \
+      --urgency low \
+      --category email.arrived \
+      --app-name "mailboxes" \
+      "New email in ${name}" \
+      "You have ${new_email} new email(s) in ${name}. Total unread is ${unread_after}."
   fi
+
+  flock -u "$lock_fd"
 }
 
 index_and_tag_emails() {
@@ -194,28 +195,6 @@ read_status() {
     cat "${mail_dir}/${box}/.mailboxes-state"
   else
     echo ""
-  fi
-}
-
-aquire_lock() {
-  local path="$1"
-
-  if [[ -f "$path" ]]; then
-    echo "Lockfile present. Aborting."
-    return 1
-  else
-    echo "" > "$path"
-    return 0
-  fi
-}
-
-unlock() {
-  local path="$1"
-  # Just to be very very sure here
-  if [[ "$path" == *-lock ]]; then
-    rm -r "$path"
-  else
-    die "That does not look like a lockfile to me: ${path}"
   fi
 }
 
